AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

# Offense count: 1
Lint/Eval:
  Enabled: false

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 140

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 5

# Offense count: 39
# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 140

# Offense count: 22
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

# Offense count: 161
Style/AsciiComments:
  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

# Offense count: 144
Style/Documentation:
  Enabled: false

# Offense count: 104
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: false

# Offense count: 100
# Cop supports --auto-correct.
Style/EmptyLinesAroundBody:
  Enabled: false

# Offense count: 65
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: true

# Offense count: 8
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 11

# Offense count: 28
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: false

# Offense count: 2
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 148
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 42
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 314
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 108
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 116
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

# Offense count: 35
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: false


Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ActionFilter:
  Enabled: false

Style/AmbiguousRegexpLiteral:
  Enabled: false
